# TCL File Generated by Component Editor 17.0
# Sun Oct 22 16:49:08 CEST 2017
# DO NOT MODIFY


# 
# LCD "LCD" v1.0
#  2017.10.22.16:49:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD
# 
set_module_property DESCRIPTION ""
set_module_property NAME LCD
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LCD
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LcdDriver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fifo.vhdl VHDL PATH fifo.vhdl
add_fileset_file lcdDriver.vhdl VHDL PATH lcdDriver.vhdl TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink Clk_CI clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink Reset_NRI reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end Cs_NSO chipselect Output 1
add_interface_port conduit_end LcdReset_NRO lcdreset Output 1
add_interface_port conduit_end DB_DIO lcddata Bidir 16
add_interface_port conduit_end Rd_NSO read Output 1
add_interface_port conduit_end Wr_NSO write Output 1
add_interface_port conduit_end DC_NSO data_cmd_select Output 1
add_interface_port conduit_end IM0_SO im0 Output 1


# 
# connection point LCD_AVALON_SLAVE
# 
add_interface LCD_AVALON_SLAVE avalon end
set_interface_property LCD_AVALON_SLAVE addressUnits WORDS
set_interface_property LCD_AVALON_SLAVE associatedClock clock_sink
set_interface_property LCD_AVALON_SLAVE associatedReset reset_sink
set_interface_property LCD_AVALON_SLAVE bitsPerSymbol 8
set_interface_property LCD_AVALON_SLAVE burstOnBurstBoundariesOnly false
set_interface_property LCD_AVALON_SLAVE burstcountUnits WORDS
set_interface_property LCD_AVALON_SLAVE explicitAddressSpan 0
set_interface_property LCD_AVALON_SLAVE holdTime 0
set_interface_property LCD_AVALON_SLAVE linewrapBursts false
set_interface_property LCD_AVALON_SLAVE maximumPendingReadTransactions 1
set_interface_property LCD_AVALON_SLAVE maximumPendingWriteTransactions 0
set_interface_property LCD_AVALON_SLAVE readLatency 0
set_interface_property LCD_AVALON_SLAVE readWaitTime 1
set_interface_property LCD_AVALON_SLAVE setupTime 0
set_interface_property LCD_AVALON_SLAVE timingUnits Cycles
set_interface_property LCD_AVALON_SLAVE writeWaitTime 0
set_interface_property LCD_AVALON_SLAVE ENABLED true
set_interface_property LCD_AVALON_SLAVE EXPORT_OF ""
set_interface_property LCD_AVALON_SLAVE PORT_NAME_MAP ""
set_interface_property LCD_AVALON_SLAVE CMSIS_SVD_VARIABLES ""
set_interface_property LCD_AVALON_SLAVE SVD_ADDRESS_GROUP ""

add_interface_port LCD_AVALON_SLAVE WaitReq_SO waitrequest Output 1
add_interface_port LCD_AVALON_SLAVE Read_SI read Input 1
add_interface_port LCD_AVALON_SLAVE Write_SI write Input 1
add_interface_port LCD_AVALON_SLAVE ReadData_DO readdata Output 16
add_interface_port LCD_AVALON_SLAVE Address_DI address Input 2
add_interface_port LCD_AVALON_SLAVE WriteData_DI writedata Input 16
add_interface_port LCD_AVALON_SLAVE ByteEnable_DI byteenable Input 2
add_interface_port LCD_AVALON_SLAVE BeginBurstTransfer_DI beginbursttransfer Input 1
add_interface_port LCD_AVALON_SLAVE BurstCount_DI burstcount Input 8
add_interface_port LCD_AVALON_SLAVE ReadDataValid_SO readdatavalid Output 1
set_interface_assignment LCD_AVALON_SLAVE embeddedsw.configuration.isFlash 0
set_interface_assignment LCD_AVALON_SLAVE embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment LCD_AVALON_SLAVE embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment LCD_AVALON_SLAVE embeddedsw.configuration.isPrintableDevice 0

