# TCL File Generated by Component Editor 17.0
# Fri Nov 03 16:38:50 CET 2017
# DO NOT MODIFY


# 
# DMAMaster "DMAMaster" v1.0
#  2017.11.03.16:38:50
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DMAMaster
# 
set_module_property DESCRIPTION ""
set_module_property NAME DMAMaster
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DMAMaster
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DmaMaster
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dma.vhdl VHDL PATH dma.vhdl TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PICSIZE_BIN NATURAL 17
set_parameter_property PICSIZE_BIN DEFAULT_VALUE 17
set_parameter_property PICSIZE_BIN DISPLAY_NAME PICSIZE_BIN
set_parameter_property PICSIZE_BIN TYPE NATURAL
set_parameter_property PICSIZE_BIN UNITS None
set_parameter_property PICSIZE_BIN ALLOWED_RANGES 0:2147483647
set_parameter_property PICSIZE_BIN HDL_PARAMETER true
add_parameter PICSIZE_DEC NATURAL 76800
set_parameter_property PICSIZE_DEC DEFAULT_VALUE 76800
set_parameter_property PICSIZE_DEC DISPLAY_NAME PICSIZE_DEC
set_parameter_property PICSIZE_DEC TYPE NATURAL
set_parameter_property PICSIZE_DEC UNITS None
set_parameter_property PICSIZE_DEC ALLOWED_RANGES 0:2147483647
set_parameter_property PICSIZE_DEC HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave WaitReq_SO waitrequest Output 1
add_interface_port avalon_slave ReadData_DO readdata Output 16
add_interface_port avalon_slave BeginBurstTransfer_SI beginbursttransfer Input 1
add_interface_port avalon_slave Read_SI read Input 1
add_interface_port avalon_slave Write_SI write Input 1
add_interface_port avalon_slave ReadDataValid_SO readdatavalid Output 1
add_interface_port avalon_slave Address_DI address Input 16
add_interface_port avalon_slave BurstCount_DI burstcount Input 17
add_interface_port avalon_slave ByteEnable_DI byteenable Input 2
add_interface_port avalon_slave WriteData_DI writedata Input 16
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 1
set_interface_property avalon_master maximumPendingWriteTransactions 1
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master Master_Address_DO address Output 32
add_interface_port avalon_master Master_ReadDataValid_SI readdatavalid Input 1
add_interface_port avalon_master Master_ReadData_DI readdata Input 16
add_interface_port avalon_master Master_Read_SO read Output 1
add_interface_port avalon_master Master_WaitReq_SI waitrequest Input 1
add_interface_port avalon_master Master_WriteData_DO writedata Output 16
add_interface_port avalon_master Master_Write_SO write Output 1
add_interface_port avalon_master Master_WriteResponseValid_SI writeresponsevalid Input 1
add_interface_port avalon_master Master_BurstCount_DO burstcount Output 17
add_interface_port avalon_master Master_Response_DI response Input 2


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink Clk_CI clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink Reset_NRI reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender Master_IRQ_SO irq Output 1

