// systemFile_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.0 595

`timescale 1 ps / 1 ps
module systemFile_mm_interconnect_1 (
		input  wire        altpll_0_c0_clk,                              //                       altpll_0_c0.clk
		input  wire        CPU_reset_reset_bridge_in_reset_reset,        //   CPU_reset_reset_bridge_in_reset.reset
		input  wire [25:0] CPU_tightly_coupled_data_master_0_address,    // CPU_tightly_coupled_data_master_0.address
		input  wire [3:0]  CPU_tightly_coupled_data_master_0_byteenable, //                                  .byteenable
		input  wire        CPU_tightly_coupled_data_master_0_read,       //                                  .read
		output wire [31:0] CPU_tightly_coupled_data_master_0_readdata,   //                                  .readdata
		input  wire        CPU_tightly_coupled_data_master_0_write,      //                                  .write
		input  wire [31:0] CPU_tightly_coupled_data_master_0_writedata,  //                                  .writedata
		input  wire        CPU_tightly_coupled_data_master_0_clken,      //                                  .clken
		output wire [9:0]  TCDM_s1_address,                              //                           TCDM_s1.address
		output wire        TCDM_s1_write,                                //                                  .write
		input  wire [31:0] TCDM_s1_readdata,                             //                                  .readdata
		output wire [31:0] TCDM_s1_writedata,                            //                                  .writedata
		output wire [3:0]  TCDM_s1_byteenable,                           //                                  .byteenable
		output wire        TCDM_s1_chipselect,                           //                                  .chipselect
		output wire        TCDM_s1_clken                                 //                                  .clken
	);

	wire         cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_waitrequest;   // TCDM_s1_translator:uav_waitrequest -> CPU_tightly_coupled_data_master_0_translator:uav_waitrequest
	wire  [31:0] cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_readdata;      // TCDM_s1_translator:uav_readdata -> CPU_tightly_coupled_data_master_0_translator:uav_readdata
	wire         cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_debugaccess;   // CPU_tightly_coupled_data_master_0_translator:uav_debugaccess -> TCDM_s1_translator:uav_debugaccess
	wire  [25:0] cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_address;       // CPU_tightly_coupled_data_master_0_translator:uav_address -> TCDM_s1_translator:uav_address
	wire         cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_read;          // CPU_tightly_coupled_data_master_0_translator:uav_read -> TCDM_s1_translator:uav_read
	wire   [3:0] cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_byteenable;    // CPU_tightly_coupled_data_master_0_translator:uav_byteenable -> TCDM_s1_translator:uav_byteenable
	wire         cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_readdatavalid; // TCDM_s1_translator:uav_readdatavalid -> CPU_tightly_coupled_data_master_0_translator:uav_readdatavalid
	wire         cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_lock;          // CPU_tightly_coupled_data_master_0_translator:uav_lock -> TCDM_s1_translator:uav_lock
	wire         cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_write;         // CPU_tightly_coupled_data_master_0_translator:uav_write -> TCDM_s1_translator:uav_write
	wire  [31:0] cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_writedata;     // CPU_tightly_coupled_data_master_0_translator:uav_writedata -> TCDM_s1_translator:uav_writedata
	wire         cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_clken;         // CPU_tightly_coupled_data_master_0_translator:uav_clken -> TCDM_s1_translator:uav_clken
	wire   [2:0] cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_burstcount;    // CPU_tightly_coupled_data_master_0_translator:uav_burstcount -> TCDM_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (26),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (26),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (0),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) cpu_tightly_coupled_data_master_0_translator (
		.clk                    (altpll_0_c0_clk),                                                                      //                       clk.clk
		.reset                  (CPU_reset_reset_bridge_in_reset_reset),                                                //                     reset.reset
		.uav_address            (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.uav_clken              (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_clken),         //                          .clken
		.av_address             (CPU_tightly_coupled_data_master_0_address),                                            //      avalon_anti_master_0.address
		.av_byteenable          (CPU_tightly_coupled_data_master_0_byteenable),                                         //                          .byteenable
		.av_read                (CPU_tightly_coupled_data_master_0_read),                                               //                          .read
		.av_readdata            (CPU_tightly_coupled_data_master_0_readdata),                                           //                          .readdata
		.av_write               (CPU_tightly_coupled_data_master_0_write),                                              //                          .write
		.av_writedata           (CPU_tightly_coupled_data_master_0_writedata),                                          //                          .writedata
		.av_clken               (CPU_tightly_coupled_data_master_0_clken),                                              //                          .clken
		.av_waitrequest         (),                                                                                     //               (terminated)
		.av_burstcount          (1'b1),                                                                                 //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                 //               (terminated)
		.av_begintransfer       (1'b0),                                                                                 //               (terminated)
		.av_chipselect          (1'b0),                                                                                 //               (terminated)
		.av_readdatavalid       (),                                                                                     //               (terminated)
		.av_lock                (1'b0),                                                                                 //               (terminated)
		.av_debugaccess         (1'b0),                                                                                 //               (terminated)
		.uav_response           (2'b00),                                                                                //               (terminated)
		.av_response            (),                                                                                     //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                 //               (terminated)
		.av_writeresponsevalid  ()                                                                                      //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (10),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (26),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (1),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) tcdm_s1_translator (
		.clk                    (altpll_0_c0_clk),                                                                      //                      clk.clk
		.reset                  (CPU_reset_reset_bridge_in_reset_reset),                                                //                    reset.reset
		.uav_address            (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.uav_clken              (cpu_tightly_coupled_data_master_0_translator_avalon_universal_master_0_clken),         //                         .clken
		.av_address             (TCDM_s1_address),                                                                      //      avalon_anti_slave_0.address
		.av_write               (TCDM_s1_write),                                                                        //                         .write
		.av_readdata            (TCDM_s1_readdata),                                                                     //                         .readdata
		.av_writedata           (TCDM_s1_writedata),                                                                    //                         .writedata
		.av_byteenable          (TCDM_s1_byteenable),                                                                   //                         .byteenable
		.av_chipselect          (TCDM_s1_chipselect),                                                                   //                         .chipselect
		.av_clken               (TCDM_s1_clken),                                                                        //                         .clken
		.av_read                (),                                                                                     //              (terminated)
		.av_begintransfer       (),                                                                                     //              (terminated)
		.av_beginbursttransfer  (),                                                                                     //              (terminated)
		.av_burstcount          (),                                                                                     //              (terminated)
		.av_readdatavalid       (1'b0),                                                                                 //              (terminated)
		.av_waitrequest         (1'b0),                                                                                 //              (terminated)
		.av_writebyteenable     (),                                                                                     //              (terminated)
		.av_lock                (),                                                                                     //              (terminated)
		.av_debugaccess         (),                                                                                     //              (terminated)
		.av_outputenable        (),                                                                                     //              (terminated)
		.uav_response           (),                                                                                     //              (terminated)
		.av_response            (2'b00),                                                                                //              (terminated)
		.uav_writeresponsevalid (),                                                                                     //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                  //              (terminated)
	);

endmodule
